import re
import requests
from bs4 import BeautifulSoup
from pytubefix  import YouTube

def extract_video_id(url):
    """Extract YouTube video ID from URL"""
    pattern = r'(?:v=|\/)([0-9A-Za-z_-]{11})'
    match = re.search(pattern, url)
    return match.group(1) if match else None

def get_video_info(url):
    """Get video title, transcript and thumbnail"""
    video_id = extract_video_id(url)
    if not video_id:
        return {"error": "Invalid YouTube URL"}
    
    try:
        # Get title using pytubefix
        video = YouTube(url)
        title = video.title        
        # Get thumbnail
        thumbnail_url = f"https://img.youtube.com/vi/{video.video_id}/maxresdefault.jpg"
        
        # Get transcript (autogenerated)
        caption = [lang for lang in list(video.captions.keys()) if "a." in lang.code][0]
        transcript = caption.generate_srt_captions()
        
        return {
            "title": title,
            "transcript": transcript,
            "caption_language": str(caption.code).replace('a.',''),
            "thumbnail_url": thumbnail_url,
            "video_id": video_id
        }
    except Exception as e:
        return {"error": str(e)}

if __name__ == "__main__":
    test_url = "https://www.youtube.com/watch?v=_1f-o0nqpEI&t"
    result = get_video_info(test_url)
    print(f"Title: {result.get('title')}")
    print(f"Transcript: {result.get('transcript', '')[:150]}...") 
    print(f"Thumbnail URL: {result.get('thumbnail_url')}")
    print(f"Video ID: {result.get('video_id')}")